### PR TITLE
improve dynamic inputs

### PR DESCRIPTION
**Pull request by pterrien**
As discussed previously (issue #213 and discussion #218), this PR aims at improving the dynamic input approach a bit:
- add options to set custom separator and start index (e.g. `arg0`)
  - modified the options (in `setupDynamicConnections()` and `dynamic_connection()`) accordingly
- allow static inputs to coexist with dynamic ones
- preserve input label if it exists

### CODE REVIEW

**Comment by melMass** [comment]
Thanks Terrien!
I will be able to test it properly tomorrow!

**Review by melMass — APPROVED** [review]
Thanks! It works great and fix the > 1 static widget/input.
I'll work on some tests next to make it easier to catch edge cases.

**Comment by pterrien** [comment]
That's great, happy to read this!
In the meantime, as I worked on my own nodes, I had the opportunity to dig into the JS part of Comfy and got more comfortable with it (for example, to create outputs dynamically).
So I think we should be able to deal with some more advanced issues, like ensuring that static inputs (or widgets converted to inputs) are listed before the dynamic ones. That won't be easy for sure, but probably feasible.
I you're interested, I should have some time in a few weeks, don't hesitate to ping me.

**Comment by melMass** [comment]
Dynamic Outputs? That's something I tried many times before, I'd love to read your solution!

Great I will ping you once I've setup the tests I will take inspiration from the official [tests](https://github.com/Comfy-Org/ComfyUI_frontend/tree/431ad7d27f54e470f4336543b8d892bab9bf63d3/tests-ui) used on https://ci.comfy.org/

**Comment by pterrien** [comment]
Yes, I'm having fun :)
Basically I'm working on a node to load a user-defined JSON file (with CFG, seed, prompt, ... anything the user put into it), to quickly apply new values: this would allow having a bunch of different config files (for example test cases), without having to change values manually in the workflow.
I must admit, I had to inspect the Comfy/LiteGraph code and rgthree typings, but basically the core stuff is as simple as:
```javascript
const output = node.addOutput(name, type) // type is like in python, ie "STRING", "*", or ["INT", "FLOAT"]
output.label = "my super label" // you can even set the label. Still struggling with the tooltip though...
```

I also played with other stuff, like an hidden widget, server/client messages that work with multiple browser windows / tabs (because by default they don't), ...

Everything should be accessible in a few weeks, as I plan to create my own repo: I have developed a pretty nice XY Plot I think, with many many features like RGBA (to allow having a custom bg image), auto-queueing, page header / footer with templating, works with different image sizes... and more importantly: no BS custom KSampler or such, you use the nodes you want to generate the images. You can even just load images from a folder, for example.
But if you want, I can share all that with you in advance, just drop me a mail or cloud drive.

Regarding this, if you don't mind, maybe I will ask for your advice in the near future. I'm pretty new to this community, so I don't really know how to properly share my work. I think that posting on reddit (and of course registering on ComfyUI-Manager) could do it, but should I also spend some time on discord / matrix?

I'm also thinking about creating another repo / website, for people to exchange about nice code tricks: to say the least, I found the documentation to be very light (comfy.org is a nice introduction but probably not enough), and having to analyze the code from other extensions or Comfy/LiteGraph  is probably something most people won't do. I find this a bit frustrating TBH.
I don't pretend for a revolution here, just a way to humbly share my findings and contribute to the community. If you think that would be a good idea, I'll probably go for it. And we could even think about a shared project if you're interested?

Sorry, that was a long post... I will just finish by wishing you some happy EoY celebrations (if applicable to your country / religion), and thank you for your kind messages: be sure, they truly made me want to contribute myself.

Cheers friend, or as we say in French: "Passe de bonnes fêtes l'ami!".

**Comment by melMass** [comment]
Sounds awesome! XY Plot is something I'd love to see improved in Comfy!

> Regarding this, if you don't mind, maybe I will ask for your advice in the near future

Don't hesitate but yes I think Reddit is a great place to get it seen, Even if clunky, posting at least one version on CivitAi could also bring new users.
As for discords I recommend 2:
- The official ComfyOrg one (the matrix is relayed there anyway): https://discord.gg/MNdrXgZrGc
- Banodoco (a well organized server with many golden info): https://discord.gg/QwvK75qNJx

> I'm also thinking about creating another repo / website, for people to exchange about nice code tricks: to say the least, I found the documentation to be very light (comfy.org is a nice introduction but probably not enough), and having to analyze the code from other extensions or Comfy/LiteGraph is probably something most people won't do. I find this a bit frustrating TBH.

Completely, although I would probably try to PR to the official docs, but I can understand wanting to make your own thing! I thought about gathering some of my findings before, I try to document code and link code blocks to other devs on discord etc but it's all manual. I'd love to participate if you make your own.

>  "Passe de bonnes fêtes l'ami!".

Hehe je suis Francais :)

**Comment by pterrien** [comment]
> Hehe je suis Francais :)

Oui je m'en doutais d'après ton profil github :) Moi aussi d'ailleurs

Many thanks for the discord links, I'll check that.

About the dynamic outputs, in case you want to play on your side:
I finally managed to correct an issue I had, when connecting with some nodes, with a warning about `Exception when validating node: tuple index out of range`.
The core reason is that, in the `validate_inputs()` function of `execution.py`, it tries to get the type of my output. But, when I define my node class, the `RETURN_TYPES` is typically `()` as I cannot anticipate what will be my outputs (that's the whole point of dynamic outputs after all...).
So here is how I did:
```python
# define an "any" type, maybe it's not mandatory
class AnyType(str):
    def __ne__(self, __value: object) -> bool:
        return False
ANY_TYPE = AnyType('*')

# create a class derived from tuple, that will always return ANY_TYPE whatever the index
class ReturnTypes(tuple):
    def __getitem__(self, key):
        return ANY_TYPE # may work with a simple "*", to be tested

# in the node class
RETURN_TYPES = ReturnTypes()
```
No more warning, it seems to work properly now. In case you also have static outputs, of course you will have to adjust the `ReturnTypes` class with a proper constructor and a smarter `__getitem__()`.
Hope this helps!

**Pull request merged**
