### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
We are building a global registry for custom nodes (similar to PyPI). The registry makes using custom nodes more reliable by reserving globally unique names for each custom node, and supporting semantic versioning.

Here’s some [more information](https://www.comfydocs.org/registry/overview#introduction) on the registry.

Action Required:

- [x] Go to the [registry](https://www.comfyregistry.org/). Login and create a publisher id. Comment it here and we will update the PR (or just merge it and change it yourself).
- [x] Merge the separate Github Actions PR and run the workflow.
If you want to publish the node manually, [install the cli](https://www.comfydocs.org/comfy-cli/getting-started#install-cli) and run `comfy node publish`

Please message me on [Discord](https://discord.com/invite/comfycontrib) if you have any questions!

### CODE REVIEW

**Review by melMass — APPROVED** [review]
Thanks! 
I'll merge this one before the CI

**Comment by haohaocreates** [comment]
Hey @melMass, Saw that you merged the PR which is amazing!!!!! Just a few last steps to get you onboarded 🚀

Steps:
1. Go to the registry. [https://www.comfyregistry.org/]
2. Login and create a publisher id.
3. Update the toml file with your publisher ID, and publish your node either through the CLI or with GH Actions!

There's also like a 1minute video we made too teehee - https://youtu.be/WhOZZOgBggU

Let me know if there is anything else I can help with!!"

**Comment by melMass** [comment]
I will do it today! 
I realized I need to version up each time I push to main for the registry right?
If so I will think of a way to automate it, and probably work more with PRs

**Comment by melMass** [comment]
@haohaocreates I realize I think I already did what you asked back when we merged this?

I already have a publisher id: https://github.com/melMass/comfy_mtb/blob/fa3199be2b87bf3cb7484a0fee32a8ac099adc65/pyproject.toml#L6

https://registry.comfy.org/publishers/mel

I will fix auto version today

**Comment by haohaocreates** [comment]
Yes!!!! So if you already have a publisher ID you can skip the comfy
registry set up, and just fill in the "publisher ID" section of the toml
file without having to create another one!

Also, I got your discord message, love that you go the icon and auto
verison working hehe

**Pull request merged**
