### PR TITLE
Adjust Contrast Dynamically

### PR DESCRIPTION
**Pull request by christian-byrne**
* Updated `MTB_ColorCorrect.contrast_adjustment_tensor` to adjust contrast based on the luminance distribution within the image (rather than adjusting uniformly)
* Uses same technique as [torchvision adjust_contrast](https://pytorch.org/vision/stable/generated/torchvision.transforms.v2.functional.adjust_contrast.html#torchvision.transforms.v2.functional.adjust_contrast)

Screenshots compare current method (top) to dynamic adjustment (bottom)
high

low

### CODE REVIEW

**Review by melMass — APPROVED** [review]
LGTM!
Thanks, it looks much better.

**Comment by christian-byrne** [comment]
That's a good idea. If you know the color space, you will also know what value to use for gamma correction. It would be nice if the LoadImage node gave the metadata, then we could determine the color space automatically.

I also just realized this. If this node is meant mainly for post-processing, you could just always assume sRGB. Because AI tools will be trained on sRGB datasets, so won't they always create sRGB images? In that case we also know to use a gamma value of 2.2 - `image.pow(1.0/2.2)`

**Comment by melMass** [comment]
> I also just realized this. If this node is meant mainly for post-processing, you could just always assume sRGB. Because AI tools will be trained on sRGB datasets, so won't they always create sRGB images? In that case we also know to use a gamma value of 2.2 - `image.pow(1.0/2.2)`

The node is not specifically for "post" but you are right that we mostly deal with sRGB in Comfy (in and out)!
In this case I think all the color math in the node should be done in that space

**Comment by christian-byrne** [comment]
Thanks for the info on color spaces, that's good to learn. I'll restore the branch and switch to sRGB this weekend if you don't get to it. I like the tooling and automation in your repo, been using it to develop. I'll try to PR/issue anything useful going forward.

**Comment by melMass** [comment]
Appreciated!!
This led me to a little rabbit hole to look into the options for a proper color pipeline in comfy. I might tackle an OpenImageIO extension for Comfy soonish!

**Pull request merged**
